name: intergration-packages

on: 
  push:
    branches: ['main']


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ✅ Checkout Code
        uses: actions/checkout@v3

      - name: ✅ Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: ✅ packages version patch
        run: |
          git config --global user.email "kimhojin3714@naver.com"
          git config --global user.name "hovelopin"
          npm version patch

      - name: check name
        run: |
          NAME = ${npm whoami}
          echo "npm whoami result: $NAME"

      - name: ✅ npm publish
        run: npm publish
